version: '3.8'

services:
  payment-service:
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env 
    depends_on:
      db:
        condition: service_healthy  # Ensure payment-service waits for db to be healthy
    networks:
      - payment-network             # Added network for container communication
    restart: unless-stopped         # Added restart policy for reliability

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rot@2112002
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network             # Added network for container communication
    healthcheck:                    # Added healthcheck to ensure db readiness
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped         # Added restart policy for reliability

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge
