services:
  payment-service:
    build: .
    ports:
      - "3003:3003"
    env_file:
      - .env 
    command: sh -c "npx prisma migrate deploy && npm run start"  # run migrations at startup
    depends_on:
      db:
        condition: service_healthy  # Ensure payment-service waits for db to be healthy
    networks:
      - payment-network             # Added network for container communication
    restart: unless-stopped         # Added restart policy for reliability

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rot@2112002
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - payment-network             # Added network for container communication
    healthcheck:                    # Added healthcheck to ensure db readiness
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped         # Added restart policy for reliability

volumes:
  postgres_data:

networks:
  payment-network:
    driver: bridge
