version: "3.8"

services:
  payment-service:
    container_name: e-learning_backend-payment-service
    build: .
    ports:
      - "5002:5002"
    env_file:
      - .env
    command: sh -c "npx prisma migrate deploy && npm run start"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - e-learning-network
    restart: unless-stopped

  db:
    container_name: e-learning_backend-payment-db
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Rot@2112002
      POSTGRES_DB: payment_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - e-learning-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
  redis: 
    container_name: e-learning_backend-payment-redis
    image: redis:latest
    ports:
      - "6379:6379"
    networks:
      - e-learning-network
    restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  e-learning-network:
    external: true # Ensure this network exists or create it with `docker network create e-learning-network`
      
