name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/elearning_backend:latest --build-arg DB_URL="${{ secrets.DATABASE_URI }}" .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/elearning_backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |

            echo "Creating /app/ directory if it doesn't exist..."
            sudo mkdir -p /app
            sudo chown ubuntu:ubuntu /app

            echo "Transferring .env file..."
            echo "${{ secrets.ENV_FILE }}" | sudo tee /home/ubuntu/.env > /dev/null
            sudo mv /home/ubuntu/.env /app/.env
            sudo chmod 600 /app/.env

            echo "Pulling latest Docker image..."
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/elearning_backend:latest

            echo "Stopping old container..."
            sudo docker stop elearning_backend || true
            sudo docker rm elearning_backend || true

            echo "Pruning unused containers and images..."
            sudo docker container prune --force
            sudo docker image prune --force

            echo "Running new container..."
            sudo docker run -d -p 3001:3000 --name elearning_backend --env-file /app/.env ${{ secrets.DOCKERHUB_USERNAME }}/elearning_backend:latest

            echo "Checking logs..."
            sudo docker logs elearning_backend
