name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3
        
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Set up timestamp
        run: echo "TIMESTAMP=$(date +%Y%m%d%H%M%S)" >> $GITHUB_ENV

      - name: Build and push with timestamp
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/phantasmagoria-backend:latest -t ${{ secrets.DOCKERHUB_USERNAME }}/phantasmagoria-backend:${{ env.TIMESTAMP }} --build-arg DB_URL="${{ secrets.DATABASE_URI}}" .
          docker push --all-tags ${{ secrets.DOCKERHUB_USERNAME }}/phantasmagoria-backend
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/phantasmagoria-backend:latest
            sudo docker stop $(sudo docker container ls -q --filter "name=phantasmagoria") || true
            sudo docker container prune --force
            sudo docker image prune --force
            sudo docker run -d -p 5001:5000 --name phantasmagoria ${{ secrets.DOCKERHUB_USERNAME }}/phantasmagoria-backend:latest
            sudo docker logs $(sudo docker container ls -q --filter "name=phantasmagoria") || true
            exit
