name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/e-learning-backend:latest .
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/e-learning-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            # Create app directory if not exists
            sudo mkdir -p /app
            echo "${{ secrets.ENV_FILE }}" | sudo tee /app/.env > /dev/null
            sudo chmod 600 /app/.env
            
            # Stop and clean up old containers
            sudo docker-compose -f /app/docker-compose.yml down || true
            
            # Pull the latest image
            sudo docker pull ${{ secrets.DOCKERHUB_USERNAME }}/e-learning-backend:latest
            
            # Start services using docker-compose
            cd /app
            echo "${{ secrets.DOCKER_COMPOSE_FILE }}" | sudo tee /app/docker-compose.yml > /dev/null
            sudo docker-compose up -d
            
            # Verify services are running
            sudo docker ps
            sudo docker logs e-learning-backend